### ISSUE TITLE
When sending a file to Sharepoint and S3, if sharepoint is defined first, the S3 transfer fails

### ISSUE THREAD

**Issue by adammcdonagh** [adammcdonagh/open-task-framework#100]
```
sh-5.2$ cat 20240923-171111.266_T_T-XXXXXX_failed.log 
2024-09-23 17:11:14,803 — INFO - opentaskpy.taskhandlers.transfer.T-XXXXXX - transfer.py:205 [T-XXXXXX_0] — Running transfer
2024-09-23 17:11:17,058 — INFO - opentaskpy.taskhandlers.transfer.T-XXXXXX - transfer.py:288 [T-XXXXXX_0] — Performing a file watch on <SOMEFILE>
...
...
2024-09-23 17:11:22,859 — ERROR - opentaskpy.taskhandlers.transfer.T-XXXXXX - transfer.py:130 [T-XXXXXX_0] — 'bucket'
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/opentaskpy/taskhandlers/batch.py", line 475, in _execute
    result = task_handler.run(kill_event=event)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/opentaskpy/taskhandlers/transfer.py", line 540, in run
    transfer_result = self.source_remote_handler.transfer_files(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/opentaskpy/addons/aws/remotehandlers/s3.py", line 437, in transfer_files
    f" {dest_remote_handler.spec['bucket']}/{file_name}"
        ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'bucket'
2024-09-23 17:11:22,860 — ERROR - opentaskpy.taskhandlers.transfer.T-XXXXXX - taskhandler.py:41 [T-XXXXXX_0] — 'bucket'
```

**Comment by adammcdonagh** [comment]
Fixed by #104
