### ISSUE TITLE
SFTP Connectivity Issues

### ISSUE THREAD

**Issue by adammcdonagh** [adammcdonagh/open-task-framework#88]
```
2024-06-15 09:07:32,572 — INFO - opentaskpy.remotehandlers.sftp.XXXXXXXX - sftp.py:90 [XXXXXXXX_0] — Using private key from task spec
2024-06-15 09:07:35,797 — INFO - opentaskpy.remotehandlers.sftp.XXXXXXXX - sftp.py:122 [XXXXXXXX_0] — Connecting to <SFTP_HOSTNAME>
2024-06-15 09:07:35,886 — INFO - opentaskpy.remotehandlers.sftp.XXXXXXXX.paramiko.transport - transport.py:1909 [Thread-44] — Connected (version 2.0, client OpenSSH_8.0)
2024-06-15 09:07:36,093 — INFO - opentaskpy.remotehandlers.sftp.XXXXXXXX.paramiko.transport - transport.py:1909 [Thread-44] — Authentication (publickey) successful!
2024-06-15 09:07:39,465 — ERROR - opentaskpy.remotehandlers.sftp.XXXXXXXX - sftp.py:133 [XXXXXXXX_0] — Unable to connect to <SFTP_HOSTNAME>: Timeout opening channel.
2024-06-15 09:07:39,468 — WARNING - opentaskpy.remotehandlers.sftp.XXXXXXXX.paramiko.transport - transport.py:1909 [Thread-44] — Success for unrequested channel! [??]
2024-06-15 09:07:43,466 — INFO - opentaskpy.remotehandlers.sftp.XXXXXXXX - sftp.py:122 [XXXXXXXX_0] — Connecting to <SFTP_HOSTNAME>
2024-06-15 09:07:46,783 — INFO - opentaskpy.remotehandlers.sftp.XXXXXXXX.paramiko.transport - transport.py:1909 [Thread-50] — Connected (version 2.0, client OpenSSH_8.0)
2024-06-15 09:07:46,784 — ERROR - opentaskpy.remotehandlers.sftp.XXXXXXXX - sftp.py:133 [XXXXXXXX_0] — Unable to connect to <SFTP_HOSTNAME>: No existing session
2024-06-15 09:07:50,787 — INFO - opentaskpy.remotehandlers.sftp.XXXXXXXX - sftp.py:122 [XXXXXXXX_0] — Connecting to <SFTP_HOSTNAME>
2024-06-15 09:07:50,855 — INFO - opentaskpy.remotehandlers.sftp.XXXXXXXX.paramiko.transport - transport.py:1909 [Thread-58] — Connected (version 2.0, client OpenSSH_8.0)
2024-06-15 09:07:54,178 — ERROR - opentaskpy.remotehandlers.sftp.XXXXXXXX - sftp.py:133 [XXXXXXXX_0] — Unable to connect to <SFTP_HOSTNAME>: No existing session
2024-06-15 09:07:54,183 — ERROR - opentaskpy.taskhandlers.transfer.XXXXXXXX - transfer.py:130 [XXXXXXXX_0] — No existing session
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/opentaskpy/taskhandlers/batch.py", line 474, in _execute
    result = task_handler.run(kill_event=event)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/opentaskpy/taskhandlers/transfer.py", line 295, in run
    remote_files = self.source_remote_handler.list_files(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/opentaskpy/remotehandlers/sftp.py", line 172, in list_files
    self.connect(self.spec["hostname"])
  File "/usr/lib/python3.12/site-packages/opentaskpy/remotehandlers/sftp.py", line 100, in connect
    self.connect_with_retry(client_kwargs)
  File "/usr/lib/python3.12/site-packages/tenacity/__init__.py", line 330, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/tenacity/__init__.py", line 467, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/tenacity/__init__.py", line 368, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/tenacity/__init__.py", line 410, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/tenacity/__init__.py", line 183, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.12/site-packages/tenacity/__init__.py", line 470, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/opentaskpy/remotehandlers/sftp.py", line 134, in connect_with_retry
    raise ex
  File "/usr/lib/python3.12/site-packages/opentaskpy/remotehandlers/sftp.py", line 129, in connect_with_retry
    ssh_client.connect(**client_kwargs)
  File "/usr/lib/python3.12/site-packages/paramiko/client.py", line 457, in connect
    server_key = t.get_remote_server_key()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/paramiko/transport.py", line 918, in get_remote_server_key
    raise SSHException("No existing session")
paramiko.ssh_exception.SSHException: No existing session
2024-06-15 09:07:54,255 — ERROR - opentaskpy.taskhandlers.transfer.XXXXXXXX - taskhandler.py:41 [XXXXXXXX_0] — No existing session
2024-06-15 09:12:39,497 — ERROR - opentaskpy.remotehandlers.sftp.XXXXXXXX.paramiko.transport - transport.py:1909 [Thread-44] — Socket exception: Connection reset by peer (104)
```

**Comment by adammcdonagh** [comment]
This appears to primarily be caused by the 3rd party SFTP server. MaxStartups can be altered if connecting to a remote host that is fairly busy.
